# Generated by Django 5.2.7 on 2025-11-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('course', models.CharField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
