# Generated by Django 5.2.7 on 2025-11-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
