# Generated by Django 5.2.7 on 2025-11-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.category'),
            preserve_default=False,
        ),
    ]
