# Generated by Django 5.2.7 on 2025-11-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_products_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='des',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
    ]
