# Generated by Django 5.2.7 on 2025-11-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_category_created_at_category_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
